### ISSUE TITLE
sepolicy duplication

### ISSUE THREAD

**Issue by Luciogi** [frstprjkt/device_xiaomi_lime#1]
Hi, I am building Arrow OS for Redmi 9t
I get this error
could you tell how to fix it?
```
[ 81% 97841/120135] //system/sepolicy:plat_policy_for_vendor.cil Building cil for plat_policy_for_vendor.cil [common]
FAILED: /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil
/mnt/HDD1/arrow/out/host/linux-x86/bin/checkpolicy -C -M -c 30 -o /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.conf/android_common/plat_policy_for_vendor.conf && cat system/sepolicy/private/technical_debt.cil >>  /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil && /mnt/HDD1/arrow/out/host/linux-x86/bin/secilc -m -M true -G -c 30 /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil -o /dev/null -f /dev/null # hash of input list: 46e7ab018d802cd45d04cddddf66d4d65f6c25fdfda90b66bf289783b7d3fe0b
device/xiaomi/lime/sepolicy/public/attributes:2:ERROR 'Duplicate declaration of type' at token ';' on line 6935:
#line 1 "device/xiaomi/lime/sepolicy/public/attributes"
attribute hal_mlipay;
checkpolicy:  error(s) encountered while parsing configuration
07:46:08 ninja failed with: exit status 1

```

**Comment by frostg-012** [comment]
> Hi, I am building Arrow OS for Redmi 9t I get this error could you tell how to fix it?
> 
> ```
> [ 81% 97841/120135] //system/sepolicy:plat_policy_for_vendor.cil Building cil for plat_policy_for_vendor.cil [common]
> FAILED: /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil
> /mnt/HDD1/arrow/out/host/linux-x86/bin/checkpolicy -C -M -c 30 -o /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.conf/android_common/plat_policy_for_vendor.conf && cat system/sepolicy/private/technical_debt.cil >>  /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil && /mnt/HDD1/arrow/out/host/linux-x86/bin/secilc -m -M true -G -c 30 /mnt/HDD1/arrow/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil -o /dev/null -f /dev/null # hash of input list: 46e7ab018d802cd45d04cddddf66d4d65f6c25fdfda90b66bf289783b7d3fe0b
> device/xiaomi/lime/sepolicy/public/attributes:2:ERROR 'Duplicate declaration of type' at token ';' on line 6935:
> #line 1 "device/xiaomi/lime/sepolicy/public/attributes"
> attribute hal_mlipay;
> checkpolicy:  error(s) encountered while parsing configuration
> 07:46:08 ninja failed with: exit status 1
> ```

u can rebuild with new changes, should be fixed.
